# Site settings
name: Caravan Windows and Doors
email: caravanwindowsanddoors@colournet.org
author: CaravanWindowsAndDoors.com

keywords: Caravan Windows Doors Replacement Static Caravan Double Glazing uVPC
description: > # this means to ignore newlines until "baseurl:"
  Caravan Windows and doors

baseurl: 
url: https://www.caravanwindowsanddoors.com

header: yes
header_sm: images/banner-small.jpg
header_med: images/banner-med.jpg
header_large: images/banner-large.jpg
header_xl: images/banner-xl.jpg

personal_name: Steve
company_name: Vulcan Windows
quote_phone: 07760 292 697
quote_email: smill13@hotmail.com


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
