# Site settings
title: Caravan Windows and Doors
email: caravanwindowsanddoors@colournet.org
author: CaravanWindowsAndDoors.com

description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.caravanwindowsanddoors.com

keywords: Caravan Windows Doors Replacement Static Caravan Double Glazing UVPC


personal_name: Paul
contact_number: 07922 123 091
quote_email: caravanwindows@btinternet.com

twitter_username:
github_username:

# Build settings
markdown: kramdown
